version: "2.0"

services:

    worker1: 
        image: worker
        ports: 
            - 8080:8080
        extra_hosts:
            - host.docker.internal:host-gateway
        environment:
            ADD: "true"
            PORT: 8080

    worker2: 
        image: worker
        ports: 
            - 8081:8081
        extra_hosts:
            - host.docker.internal:host-gateway
        environment:
            MULT: "true"
            PORT: 8081

    planner: 
        image: planner
        container_name: planner
        depends_on:
            - worker1
            - worker2
        extra_hosts:
            - host.docker.internal:host-gateway
        environment:
            TASKS: 4


    