version: "2.0"

services:

    worker: 
        image: worker
        container_name: worker
        ports: 
            - 8080:8080
        extra_hosts:
            - host.docker.internal:host-gateway
        environment:
            MULT: "true"
            ADD: "true"
            PORT: 8080

    planner: 
        image: planner
        container_name: planner
        depends_on:
            - worker
        extra_hosts:
            - host.docker.internal:host-gateway
        environment:
            TASKS: 4


    